-- Supabase Schema Migration for Online Banquet Booking System (OBBS)

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- STATES table
create table public.states (
  id bigint generated by default as identity primary key,
  state_title text not null,
  status text not null default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- CITIES table
create table public.cities (
  id bigint generated by default as identity primary key,
  state_id bigint references public.states(id) on delete cascade,
  name text not null,
  status text not null default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- EVENT TYPES table (renamed from tbleventtype)
create table public.event_types (
  id bigint generated by default as identity primary key,
  event_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- SERVICES table (renamed from tblservice)
create table public.services (
  id bigint generated by default as identity primary key,
  service_name text not null,
  description text, -- mapped from SerDes
  price numeric(10, 2), -- mapped from ServicePrice
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- PAGES table (renamed from tblpage)
create table public.pages (
  id bigint generated by default as identity primary key,
  page_type text,
  page_title text,
  page_description text,
  email text,
  mobile_number bigint,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- CONTACTS table (renamed from tblcontact)
create table public.contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  message text,
  enquiry_date timestamp with time zone default timezone('utc'::text, now()),
  is_read boolean default false
);

-- PROFILES table (Replaces tbluser, linked to Supabase Auth)
-- This table extends the default auth.users table
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  mobile_number bigint,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ADMINS table (renamed from tbladmin)
-- Ideally, admins should also be in auth.users with a role, but keeping separate for now if needed.
-- Better approach: Use a `roles` enum on profiles, but let's migrating strict structure first.
create table public.admins (
  id bigint generated by default as identity primary key,
  admin_name text,
  username text,
  mobile_number bigint,
  email text,
  password text, -- Note: specific handling needed if porting legacy passwords
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- BOOKINGS table (renamed from tblbooking)
create table public.bookings (
  id bigint generated by default as identity primary key,
  booking_id text, -- generated ID
  service_id bigint references public.services(id),
  user_id uuid references public.profiles(id), -- Linked to profiles
  booking_from date,
  booking_to date,
  event_type text,
  number_of_guests int,
  state_id bigint references public.states(id),
  city_name text, -- or reference cities(id) if possible? Legacy used name.
  message text,
  booking_date timestamp with time zone default timezone('utc'::text, now()),
  remark text,
  status text default 'Pending',
  updated_at timestamp with time zone
);

-- RLS (Row Level Security) Policies
alter table public.profiles enable row level security;
alter table public.bookings enable row level security;

-- Profiles: Users can view/edit their own profile
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Bookings: Users can view their own bookings
create policy "Users can view own bookings" on public.bookings for select using (auth.uid() = user_id);
create policy "Users can insert own bookings" on public.bookings for insert with check (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, mobile_number)
  values (new.id, new.raw_user_meta_data->>'full_name', (new.raw_user_meta_data->>'mobile_number')::bigint);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
